"""The sidebar: dataset provenance, filters and navigation.

Provenance lives here rather than in a footer because it changes how every
number on every page should be read. A synthetic dataset is a demo; a real CSV
is an analysis. That distinction must be visible before the KPIs, not after.
"""

from __future__ import annotations

from typing import Any

import streamlit as st

from components import theme
from src.services import predictor, registry


def _status_panel(status: dict[str, Any]) -> None:
    # training_status() reports None for provenance until artefacts exist, so
    # every lookup here has to tolerate a missing/None block.
    provenance = status.get("provenance") or {}
    synthetic = bool(status.get("is_synthetic") or provenance.get("is_synthetic"))

    if synthetic:
        theme.note(
            "**Synthetic demo data.** Every number here is generated by "
            "`src/synthetic.py`, not measured. Treat the shapes and relative "
            "magnitudes as realistic; do not quote the absolute values.",
            kind="warning",
        )
    else:
        theme.note(
            f"Read from `{provenance.get('path', 'unknown')}`. "
            f"{provenance.get('rows_raw', 0):,} raw rows.",
            kind="ok",
        )

    split = status.get("split") or {}
    rows = [
        # ``training_status()`` reports None (not 0) before training, so a plain
        # .get(k, 0) would still hand None to the format spec and crash the
        # sidebar for exactly the user who most needs the guidance below.
        ("Rows used", f"{status.get('rows') or 0:,}"),
        ("Clean rows", f"{provenance.get('rows_clean') or 0:,}"),
        ("Outliers held out", f"{split.get('n_outliers_excluded') or 0:,}"),
        ("Split", split.get("strategy") or "n/a"),
        ("Trained", (status.get("generated_at") or "")[:10] or "n/a"),
    ]
    st.dataframe(
        rows,
        width="stretch",
        hide_index=True,
        column_config={
            "Setting": theme.active_palette()["muted"],
            "Value": theme.active_palette()["text"],
        },
    )
    if not status.get("ready", False):
        st.error(
            "Trained model artefacts are missing. Run "
            "`python scripts/bootstrap.py` to generate the dataset and train."
        )


def sidebar(page: str = "Overview") -> dict[str, Any]:
    """Render the sidebar and return the selected filters.

    Navigation is handled by ``st.navigation`` in ``app.py``, which emits its
    own sidebar links; this function only adds the dataset panel and filters.
    ``page`` is accepted so callers can stay explicit about where they are.
    """
    del page  # navigation is declarative; see app.py
    st.sidebar.markdown("### AgriYield AI")
    st.sidebar.caption("Indian crop production & cost forecasting")

    st.sidebar.divider()
    st.sidebar.subheader("Dataset")
    with st.sidebar.expander("Provenance & model status", expanded=True):
        _status_panel(registry.training_status())

    st.sidebar.divider()
    st.sidebar.subheader("Filters")

    # Known states and crops are exposed by the predictor, not the registry.
    states = _safe_list(predictor, "known_states")
    crops = _safe_list(predictor, "crops")
    low, high = _year_range()

    filters: dict[str, Any] = {}
    with st.sidebar.expander("Geographic scope", expanded=True):
        filters["states"] = st.multiselect(
            "States / UTs", options=states, default=[],
            placeholder="All states",
        )
    with st.sidebar.expander("Crop scope", expanded=False):
        filters["crops"] = st.multiselect(
            "Crops", options=crops, default=[], placeholder="All crops",
        )
    with st.sidebar.expander("Time window", expanded=False):
        # ruff: noqa: SIM108 - not a ternary: Streamlit raises on a slider whose
        # min equals its max, so the call must be conditional, not inlined.
        if low < high:
            chosen = st.slider("Years", low, high, (low, high))
        else:
            chosen = (low, high)
        filters["year_range"] = tuple(chosen)
        filters["drop_outliers"] = st.checkbox(
            "Exclude flagged outliers", value=True,
            help=(
                "Rows the robust within-crop z-score marked as likely entry "
                "errors. Leaving them in distorts every average on the site."
            ),
        )

    st.sidebar.divider()
    left, right = st.sidebar.columns(2)
    if left.button("Light" if theme.is_dark() else "Dark", width="stretch"):
        theme.toggle_mode()
        st.rerun()
    if right.button("Reload", width="stretch", help="Clear cached artefacts"):
        registry.clear_cache()
        st.rerun()

    return filters


def apply_filters(frame, filters: dict[str, Any]):
    """Narrow a frame to the sidebar filters. Returns it unchanged if empty."""
    if frame is None or frame.empty:
        return frame
    out = frame
    states = filters.get("states") or []
    if states:
        out = out.loc[out["state"].isin(states)]
    crops = filters.get("crops") or []
    if crops:
        out = out.loc[out["crop"].isin(crops)]
    low, high = filters.get("year_range", (None, None))
    if low is not None and high is not None:
        out = out.loc[out["year"].between(int(low), int(high))]
    if filters.get("drop_outliers", True) and "is_outlier" in out.columns:
        out = out.loc[~out["is_outlier"].fillna(False).astype(bool)]
    return out


def _safe_list(module, name: str) -> list[str]:
    try:
        return list(getattr(module, name)())
    except Exception:
        return []


def _year_range() -> tuple[int, int]:
    try:
        from src.services import predictor

        low, high = predictor.year_range()
        return int(low), int(high)
    except Exception:
        from config.settings import YEAR_MAX, YEAR_MIN

        return int(YEAR_MIN), int(YEAR_MAX)
